---
- name: Install Docker distribution
  yum: name=docker-distribution state=present
  become: true
  tags:
    - registry
    - jenkins/slave

- name: Enable and run Docker Distribution
  service: name=docker-distribution enabled=yes state=started
  become: true
  tags:
    - registry
    - jenkins/slave

- name: Run UI registry container.
  become: true
  docker_container:
      image: registry.centos.org/pipeline-images/reg:latest
      name: registry-ui
      state: started
      restart: yes
      restart_policy: always
      pull: yes
      published_ports: "9000:8080"
      command: "--insecure --registry {{ public_registry }}"
