---
- name: Perform common tasks for all hosts
  hosts: all
  tasks:
      - name: Disable requiretty in sudoers
        lineinfile: dest=/etc/sudoers state=absent regexp="^Defaults requiretty.*"
        become: true
      - name: Ensure epel is enabled when enable_epel is True
        yum: name=epel-release state=present
      - name: yum update all
        yum: name='*' state=latest
      - name: Copy /etc/hosts
        synchronize: src=/etc/hosts dest=/etc/hosts
        delegate_to: localhost
      - name: SELinux permissive
        selinux: policy=targeted state=permissive
      - name: Install packages
        yum: package={{ item }} state=latest
        with_items:
            - NetworkManager
            - firewalld
            - python-rhsm-certificates
            - centos-release-openshift-origin39.noarch
            - python-ipaddress
            - docker

      - name: Start services
        systemd: state=started enabled=yes name={{ item }}
        with_items:
            - NetworkManager
            - firewalld
            - docker
      - name: Install rsync in all nodes
        yum: name=rsync state=installed
        become: true
      - name: Get all the ports open for machines in cluster
        become: true
        when: ci_setup
        firewalld:
            source: {{ cluster_subnet }}
            state: enabled
            immediate: yes
            permanent: true
            zone: public
      - name: Remove Iptables rules
        shell: iptables -F
        become: yes
        when: ci_setup
  tags:
      - cluster

- name: Confiure container registry
  hosts: nfs_registry
  tasks:
      - name: Install docker distribution
        yum: name="docker-distribution" state=latest
        become: true
      - name: Start and enable container registry
        systemd: state=started enabled=yes name="docker-distribution"
        become: true
- name: Configure NFS Server for CI
  hosts: nfs_registry
  when: setup_nfs
  roles:
      - ci_nfs/server
  tags:
      - ci_nfs/server

- name: Configure NFS clients on all the nodes for CI
  hosts: all
  when: setup_nfs
  roles:
      - ci_nfs/clients
  tags:
      - ci_nfs/clients

- name: Deploy Openshift cluster
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
  tags:
      - cluster_openshift
      - cluster

        #- name: Configure jenkins with PV and script permission
        #  hosts: openshift_master
        #  roles:
        #      - setup_jenkins
        #  tags:
        #      - jenkins
