# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ccp_server.models.base_model_ import Model
from ccp_server.models.scanner_logs import ScannerLogs  # noqa: F401,E501
from ccp_server import util


class AllScannerLogs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, scanner_name: ScannerLogs=None):  # noqa: E501
        """AllScannerLogs - a model defined in Swagger

        :param scanner_name: The scanner_name of this AllScannerLogs.  # noqa: E501
        :type scanner_name: ScannerLogs
        """
        self.swagger_types = {
            'scanner_name': ScannerLogs
        }

        self.attribute_map = {
            'scanner_name': 'scanner_name'
        }

        self._scanner_name = scanner_name

    @classmethod
    def from_dict(cls, dikt) -> 'AllScannerLogs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllScannerLogs of this AllScannerLogs.  # noqa: E501
        :rtype: AllScannerLogs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scanner_name(self) -> ScannerLogs:
        """Gets the scanner_name of this AllScannerLogs.


        :return: The scanner_name of this AllScannerLogs.
        :rtype: ScannerLogs
        """
        return self._scanner_name

    @scanner_name.setter
    def scanner_name(self, scanner_name: ScannerLogs):
        """Sets the scanner_name of this AllScannerLogs.


        :param scanner_name: The scanner_name of this AllScannerLogs.
        :type scanner_name: ScannerLogs
        """

        self._scanner_name = scanner_name
