# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ccp.apis.server.ccp_server.models.base_model_ import Model
from ccp.apis.server.ccp_server.models.project_weekly_scan_build_name_status import ProjectWeeklyScanBuildNameStatus  # noqa: F401,E501
from ccp.apis.server.ccp_server import util


class ProjectWeeklyScanBuilds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, build_number: ProjectWeeklyScanBuildNameStatus=None):  # noqa: E501
        """ProjectWeeklyScanBuilds - a model defined in Swagger

        :param build_number: The build_number of this ProjectWeeklyScanBuilds.  # noqa: E501
        :type build_number: ProjectWeeklyScanBuildNameStatus
        """
        self.swagger_types = {
            'build_number': ProjectWeeklyScanBuildNameStatus
        }

        self.attribute_map = {
            'build_number': 'build_number'
        }

        self._build_number = build_number

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectWeeklyScanBuilds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectWeeklyScanBuilds of this ProjectWeeklyScanBuilds.  # noqa: E501
        :rtype: ProjectWeeklyScanBuilds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def build_number(self) -> ProjectWeeklyScanBuildNameStatus:
        """Gets the build_number of this ProjectWeeklyScanBuilds.


        :return: The build_number of this ProjectWeeklyScanBuilds.
        :rtype: ProjectWeeklyScanBuildNameStatus
        """
        return self._build_number

    @build_number.setter
    def build_number(self, build_number: ProjectWeeklyScanBuildNameStatus):
        """Sets the build_number of this ProjectWeeklyScanBuilds.


        :param build_number: The build_number of this ProjectWeeklyScanBuilds.
        :type build_number: ProjectWeeklyScanBuildNameStatus
        """

        self._build_number = build_number
