# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ccp.apis.server.ccp_server.models.base_model_ import Model
from ccp.apis.server.ccp_server.models.project_build_name_status import\
    ProjectBuildNameStatus  # noqa: F401,E501
from ccp.apis.server.ccp_server import util


class ProjectBuilds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, build_number: ProjectBuildNameStatus=None):  # noqa: E501
        """ProjectBuilds - a model defined in Swagger

        :param build_number: The build_number of this ProjectBuilds.  # noqa: E501
        :type build_number: ProjectBuildNameStatus
        """
        self.swagger_types = {
            'build_number': ProjectBuildNameStatus
        }

        self.attribute_map = {
            'build_number': 'build_number'
        }

        self._build_number = build_number

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectBuilds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectBuilds of this ProjectBuilds.  # noqa: E501
        :rtype: ProjectBuilds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def build_number(self) -> ProjectBuildNameStatus:
        """Gets the build_number of this ProjectBuilds.


        :return: The build_number of this ProjectBuilds.
        :rtype: ProjectBuildNameStatus
        """
        return self._build_number

    @build_number.setter
    def build_number(self, build_number: ProjectBuildNameStatus):
        """Sets the build_number of this ProjectBuilds.


        :param build_number: The build_number of this ProjectBuilds.
        :type build_number: ProjectBuildNameStatus
        """

        self._build_number = build_number
