---
- name: Perform common tasks for all hosts
  hosts: all
  tasks:
    - name: Disable requiretty in sudoers
      lineinfile:  dest=/etc/sudoers state=absent regexp="^Defaults    requiretty.*"
      become: true
    - name: Enable centos admin repo when EPEL is disabled
      copy: src=centos-admin.repo dest=/etc/yum.repos.d/centos-admin.repo
      when: not enable_epel
    - name: Ensure centos admin repo is removed when epel is enabled
      file: path=/etc/yum.repos.d/centos-admin.repo state=absent
      when: enable_epel
    - name: Ensure epel is enabled when enable_epel is True
      yum: name=epel-release state=present
      when: enable_epel
    - name: Set SELinux to Permissive
      selinux:
          policy: targeted
          state: permissive
    - name: Install rsync in all nodes
      yum: name=rsync state=installed
      become: true
  tags:
    - jenkins
    - openshift

- name: Configure NFS server on scanner node for CI
  hosts: scanner_worker
  roles:
    - ci_nfs/server
  tags:
    - ci_nfs/server

- name: Configure NFS clients on all nodes for CI
  hosts: all
  roles:
    - ci_nfs/clients
  tags:
    - ci_nfs/clients

- name: Configure Jenkins nodes
  hosts: all
  roles:
    - jenkins/common
  tags:
    - jenkins

- name: Generate source code config file
  hosts: jenkins_slaves
  tasks:
    - name: Get OpenShift server ip
      shell: echo `ping {{ groups['openshift'][0] }} -c 1 | awk '{print $3}'|head -n 1|sed 's/(//'|sed 's/)//'`
      register: result

    - debug: var=result.stdout

    - set_fact:
        openshift_server_ip: "{{ result.stdout }}"

    - name: Render settings file
      template: src=settings.py.j2 dest=/tmp/cccp_settings.py

    - name: pull rendered settings file
      synchronize: src=/tmp/cccp_settings.py dest=/tmp/cccp_settings.py mode=pull rsync_opts="{{ rsync_ssh_opts}}"
  tags:
      - application
      - application/update_src

- name: Push source code to all nodes
  hosts: all
  tasks:
    - name: Copy source code to all hosts
      synchronize:
          src: ../../
          dest: /opt/cccp-service
          mode: push
          rsync_opts:
            - "{{ rsync_ssh_opts }}"
      become: true
    - name: Push config
      copy: src=/tmp/cccp_settings.py dest=/opt/cccp-service/container_pipeline/lib/settings.py
      become: true
    - name: Ensure manage.py is executable
      file: path=/opt/cccp-service/manage.py mode='g+x'
      become: true
      tags:
          - application
          - application/update_src
  tags:
      - application
      - application/update_src

- name: Setup openshift
  hosts: openshift
  roles:
    - openshift
  tags:
    - openshift

- name: Setup database
  hosts: jenkins_master
  roles:
      - django
      - db
  tags:
      - db
      - django
      - repo_tracking
      - jenkins
      - jenkins/slaves
      - jenkins/master

- name: Setup API Server
  hosts: jenkins_slaves
  roles:
      - django
      - db
      - api
  tags:
      - db
      - django
      - repo_tracking
      - api
      - jenkins
      - jenkins/slave

- name: Setup Scanner Worker
  hosts: scanner_worker
  roles:
    - django
    - scanner
  tags:
    - scanner
    - atomic/scanner

- name: Setup jenkins slaves
  hosts: jenkins_slaves
  roles:
    - django
    - jenkins/slave
    - registry
    - nginx
  tags:
    - jenkins
    - jenkins/slaves

- name: Setup jenkins master
  hosts: jenkins_master
  roles:
    - django
    - jenkins/master
  tags:
    - jenkins
    - jenkins/master

- name: Setup repo tracking
  hosts: jenkins_master
  roles:
      - django
      - repo_tracking
  tags:
      - repo_tracking

- name: Run tasks for CI
  hosts: jenkins_master
  roles:
    - ci
  tags:
    - test
