---
- name: Disable requiretty in sudoers
  hosts: all
  tasks:
    - name: Disable requiretty in sudoers
      lineinfile:  dest=/etc/sudoers state=absent regexp="^Defaults    requiretty.*"
      sudo: yes
    - name: Enable centos admin repo when EPEL is disabled
      copy: src=centos-admin.repo dest=/etc/yum.repos.d/centos-admin.repo
      when: not enable_epel
    - name: Set SELinux to Permissive
      selinux:
          policy: targeted
          state: permissive
  tags:
    - jenkins
    - openshift

- name: Configure NFS server on scanner node for CI
  hosts: scanner_worker
  roles:
    - ci_nfs/server
  tags:
    - ci_nfs/server

- name: Configure NFS clients on all nodes for CI
  hosts: all
  roles:
    - ci_nfs/clients
  tags:
    - ci_nfs/clients

- name: Configure Jenkins nodes
  hosts: all
  roles:
    - jenkins/common
  tags:
    - jenkins

- name: Setup openshift
  hosts: openshift
  roles:
    - openshift
  tags:
    - openshift

- name: Setup Scanner Worker
  hosts: scanner_worker
  roles:
    - scanner
  tags:
    - scanner
    - atomic/scanner

- name: Setup jenkins slaves
  hosts: jenkins_slaves
  roles:
    - jenkins/slave
    - registry
    - nginx
  tags:
    - jenkins
    - jenkins/slaves

- name: Setup jenkins master
  hosts: jenkins_master
  roles:
    - jenkins/master
  tags:
    - jenkins
    - jenkins/master

- name: Setup repo tracking
  hosts: jenkins_master
  roles:
      - repo_tracking
  tags:
      - repo_tracking
