---
- name: Install nfs-utils for NFS sharing
  when: setup_nfs
  become: true
  yum: name=nfs-utils state=present
  tags:
  - ci_nfs
  - test

- name: Create NFS mount directory
  when: setup_nfs
  become: true
  file:
    path: /srv/pipeline-logs
    state: directory
    mode: 0777
  tags:
  - ci_nfs
  - test

- name: Mount NFS share on the node
  when: setup_nfs
  become: true
  mount:
    name: /srv/pipeline-logs
    src: "{{ test_nfs_share }}"
    fstype: nfs
    state: mounted
  tags:
  - ci_nfs
  - test
