FROM registry.centos.org/centos/centos
MAINTAINER CentOS Community Container Pipeline<container-group@centos.org>

RUN yum update -y && \
    yum install python -y && \
    yum install PyYAML -y && \
    yum clean all

RUN mkdir -p /run_worker

ADD beanstalkc.py ca.crt node.kubeconfig worker_start_build.py \
 worker_start_delivery.py worker_dispatcher.py config.py lib.py /run_worker/
ADD oc /usr/bin/

RUN chmod a+x /usr/bin/oc /run_worker/*

WORKDIR /run_worker
