FROM registry.centos.org/centos/centos
MAINTAINER Bamacharan Kundu<bkundu@redhat.com>
RUN yum update -y && \
    yum install python -y && \
    yum clean all

RUN mkdir -p /run_worker
ADD beanstalkc.py ca.crt node.kubeconfig worker_start_delivery.py /run_worker/
ADD oc /usr/bin
RUN chmod a+x /usr/bin/oc /run_worker/*

WORKDIR /run_worker

CMD ["/run_worker/worker_start_delivery.py"]
