FROM registry.centos.org/centos/centos
MAINTAINER CentOS Community Container Pipeline<container-group@centos.org>

RUN yum update -y && \
    yum install python -y && \
    yum clean all

RUN mkdir -p /run_worker
ADD beanstalkc.py ca.crt node.kubeconfig worker_start_test.py /run_worker/
ADD oc /usr/bin/
RUN chmod a+x /usr/bin/oc /run_worker/*

WORKDIR /run_worker

CMD ["/run_worker/worker_start_build.py"]
