---
- hosts: localhost
  tasks:
    - name: Create maintenance window at Zabbix before (re)deployments
      when: zabbix_create
      zabbix_maintenance:
        name: "{{ zabbix_name }}"
        desc: "{{ zabbix_name }}"
        server_url: "{{ zabbix_server_url }}"
        state: present
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        minutes: "{{ zabbix_minutes }}"
        collect_data: False
        host_groups:
          - "{{ zabbix_host_groups }}"
      tags:
        - zabbix
