# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text=b'Image name', max_length=200, unique=True)),
                ('to_build', models.BooleanField(db_index=True, default=False, help_text=b'Whether to build image or not')),
                ('scanned', models.BooleanField(db_index=True, default=False, help_text=b'Whether the image is scanner')),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'container_images',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text=b'Package name', max_length=200)),
                ('arch', models.CharField(db_index=True, help_text=b'Architecture', max_length=20)),
                ('version', models.CharField(help_text=b'Version', max_length=100)),
                ('release', models.CharField(help_text=b'Release', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='RepoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseurls', models.TextField(db_index=True, help_text=b'Repo urls', max_length=2000, unique=True)),
                ('basearch', models.CharField(db_index=True, max_length=20)),
                ('releasever', models.CharField(db_index=True, max_length=10)),
                ('infra', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'repo_info',
            },
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('name', 'arch', 'version', 'release')]),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='packages',
            field=models.ManyToManyField(help_text=b'Packages', related_name='images', to='container_pipeline.Package'),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='parents',
            field=models.ManyToManyField(help_text=b'Parent images', to='container_pipeline.ContainerImage'),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='repoinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='container_pipeline.RepoInfo'),
        ),
    ]
