# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(blank=True, choices=[(b'queued', b'Queued'), (b'processing', b'In process'), (b'complete', b'Complete'), (b'error', b'Error'), (b'failed', b'Failed')], db_index=True, max_length=20)),
                ('logs', models.CharField(max_length=200, null=True)),
                ('notification_status', models.CharField(blank=True, choices=[(b'queued', b'Queued'), (b'sent', b'Sent'), (b'failed', b'Failed')], db_index=True, default=b'', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, default=None)),
                ('end_time', models.DateTimeField(blank=True, default=None)),
                ('trigger', models.CharField(blank=True, default=None, max_length=20)),
                ('trigger_details', models.TextField(blank=True, default=None, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'builds',
            },
        ),
        migrations.CreateModel(
            name='BuildPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[(b'build', b'Build'), (b'test', b'Test'), (b'scan', b'Scan'), (b'delivery', b'Delivery')], db_index=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[(b'queued', b'Queued'), (b'processing', b'In process'), (b'complete', b'Complete'), (b'error', b'Error'), (b'failed', b'Failed')], db_index=True, max_length=20)),
                ('start_time', models.DateTimeField(blank=True, default=None)),
                ('end_time', models.DateTimeField(blank=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container_pipeline.Build')),
            ],
            options={
                'db_table': 'build_phases',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container_pipeline.Project'),
        ),
    ]
