# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0002_auto_20170623_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uuid',
        ),
    ]
