# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0003_remove_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='buildphase',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='buildphase',
            name='phase',
            field=models.CharField(choices=[(b'dockerlint', b'Docker lint'), (b'build', b'Build'), (b'test', b'Test'), (b'scan', b'Scan'), (b'delivery', b'Delivery')], db_index=True, max_length=20),
        ),
    ]
