# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0004_auto_20171002_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='trigger',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='trigger_details',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
