# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0005_auto_20171002_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='buildphase',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
