# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0006_auto_20171003_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='trigger_details',
        ),
        migrations.AddField(
            model_name='build',
            name='service_debug_logs',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buildphase',
            name='log_file_path',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='trigger',
            field=models.TextField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='buildphase',
            name='status',
            field=models.CharField(blank=True, choices=[(b'queued', b'Queued'), (b'processing', b'In process'), (b'requeuedparent', b'Re-queued due to parent'), (b'complete', b'Complete'), (b'error', b'Error'), (b'failed', b'Failed')], db_index=True, max_length=20),
        ),
    ]
