# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_pipeline', '0007_auto_20180110_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='weekly_scan',
            field=models.BooleanField(default=False),
        ),
    ]
