FROM centos

RUN yum -y install docker
RUN yum -y install git

ADD run.sh /usr/bin/
ADD cccp_reader.py /

RUN mkdir -p /tube_request/

ADD beanstalkc.py /tube_request/

ADD send_failed_notify_request.py /tube_request/

CMD run.sh
