FROM centos

RUN yum -y install docker-1.10.3-59.el7.centos.x86_64

ADD run-delivery.sh /usr/bin/

RUN mkdir -p /tube_request/

ADD beanstalkc.py send_notify_request.py /tube_request/

CMD run-delivery.sh
