FROM centos

RUN yum -y install docker-1.10.3-59.el7.centos.x86_64 git PyYAML libyaml

ADD run.sh /usr/bin/
ADD cccp_reader.py /

RUN mkdir -p /tube_request/

ADD beanstalkc.py send_failed_notify_request.py /tube_request/

CMD run.sh
