FROM registry.centos.org/centos/centos
MAINTAINER CentOS Container Pipeline Service <container-group@centos.org>

RUN yum -y install docker; yum clean all

ADD run-test.sh /usr/bin/

RUN mkdir -p /tube_request/

ADD beanstalkc.py send_scan_request.py send_failed_notify_request.py /tube_request/

CMD run-test.sh
