FROM centos

RUN yum -y update

RUN yum -y install docker

RUN yum -y install wget mailx postfix rsyslog

RUN mkdir -p /mail_service/

ADD mail-config.sh /mail_service/

ADD worker_notify_user.py /mail_service/
ADD beanstalkc.py /mail_service/

RUN chmod 777 /mail_service/*

CMD python /mail_service/worker_notify_user.py
