FROM registry.centos.org/centos/centos

MAINTAINER CentOS Container Pipeline Service <container-group@centos.org>

RUN yum -y install docker git PyYAML libyaml; yum clean all

ADD run.sh /usr/bin/
ADD cccp_reader.py /

RUN mkdir -p /tube_request/

ADD beanstalkc.py /tube_request/

CMD run.sh
