FROM registry.centos.org/centos/centos
MAINTAINER CentOS Container Pipeline Service <container-group@centos.org>

RUN yum -y install docker; yum clean all

ADD run-delivery.sh /usr/bin/

RUN mkdir -p /tube_request/

ADD beanstalkc.py send_notify_request.py /tube_request/

CMD run-delivery.sh
