---
- name: Create secret key if not already there
  shell: docker run --rm {{ sentry_container_image }} config generate-secret-key > sentry.key
  become: true
  run_once: true

- name: Load sentry secret key into vars
  shell: cat sentry.key
  register: secret_result
  become: true

- name: Run sentry upgrade
  shell: >
      docker run --rm
      -e SENTRY_DB_USER={{ sentry_db_user }}
      -e SENTRY_DB_PASSWORD={{ sentry_db_password }}
      -e SENTRY_DB_NAME={{ sentry_db_name }}
      -e SENTRY_SECRET_KEY='{{ secret_result.stdout }}'
      --link sentry-postgres:postgres
      --link sentry-redis:redis
      {{ sentry_container_image }} upgrade --noinput
  become: true

- name: Create super user for sentry
  shell: >
      docker run --rm
      -e SENTRY_DB_USER={{ sentry_db_user }}
      -e SENTRY_DB_PASSWORD={{ sentry_db_password }}
      -e SENTRY_DB_NAME={{ sentry_db_name }}
      -e SENTRY_SECRET_KEY='{{ secret_result.stdout }}'
      --link sentry-postgres:postgres
      --link sentry-redis:redis
      {{ sentry_container_image }} createuser --email {{ sentry_admin_email }} --password {{ sentry_admin_password }} --superuser --no-input
  ignore_errors: yes
  become: true
