---
  - name: Enable epel repo
    become: true
    yum: name=epel-release state=present
    when: enable_epel
    tags:
      - nginx
      - jenkins/slave

  - name: Install nginx
    become: true
    yum: name=nginx state=present
    tags:
      - nginx
      - jenkins/slave

  - name: Copy SSL certs
    become: true
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
        - { src: "{{ ssl_key_template }}", dest: "{{ ssl_key_file }}" }
        - { src: "{{ ssl_cert_template }}", dest: "{{ ssl_cert_file }}" }
    when: copy_ssl_certs
    tags:
      - nginx
      - jenkins/slave


  - name: Copy nginx conf for CentOS registry
    become: true
    template: src={{ nginx_conf_template }} dest=/etc/nginx/conf.d/{{ nginx_conf_filename }}
    tags:
      - nginx
      - jenkins/slave

  - name: Reload nginx systemd service
    become: true
    systemd: name=nginx state=reloaded
    tags:
      - nginx
      - jenkins/slave

  - name: restart nginx
    become: true
    service: name=nginx state=restarted enabled=yes
    tags:
      - nginx
      - jenkins/slave

