FROM registry.access.redhat.com/rhel7

LABEL INSTALL='docker run --rm --privileged -v /etc/atomic.d/:/host/etc/atomic.d/ $IMAGE sh /install.sh'

# Install python-docker-py to spin up container using scan script
RUN yum -y update && yum clean all

ADD rpm-verify /
ADD rpm_verify.py /
ADD install.sh /
