apiVersion: "v1"
kind: "Template"
metadata:
  name: "container-index-seed-pipeline"
objects:
  - apiVersion: "v1"
    kind: "BuildConfig"
    metadata:
        name: seed-job
    spec:
      source:
        type: Git
        git:
          uri: "https://github.com/dharmit/ccp-openshift"
          ref: ${PIPELINE_BRANCH}
        contextDir: "seed-job"
      strategy:
        type: "JenkinsPipeline"
        jenkinsPipelineStrategy:
          jenkinsfilePath: "Jenkinsfile"
          env:
          - name: CONTAINER_INDEX_LOCATION
            value: https://github.com/dharmit/ccp-openshift-index
          - name: CONTAINER_INDEX_BRANCH
            value: master
          - name: PIPELINE_TARGET_DIR
            value: "source"
          - name: JENKINSFILE_GIT_BRANCH
            value: ${JENKINSFILE_GIT_BRANCH}
          - name: REGISTRY_URL
            value: ${REGISTRY_URL}
      triggers:
          - type: ConfigChange
parameters:
- description: "Pipeline repo branch to build off"
  displayName: Pipeline repo branch
  name: PIPELINE_BRANCH
- description: Git repo branch containing the Jenkinsfile
  displayName: Jenkinsfile repo branch
  name: JENKINSFILE_GIT_BRANCH
  required: true
  value: master
- description: URL of the registry to which image is to be pushed
  name: REGISTRY_URL
  displayName: Registry URL
