---
- name: Remove all containers
  sudo: yes
  shell: docker rm -f `docker ps -a -q`

- name: Remove /var/lib/atomic/* directory contents
  sudo: yes
  shell: rm -rf /var/lib/atomic/*

- name: Remove /var/lib/docker/volumes/* directory contents
  sudo: yes
  shell: rm -rf /var/lib/docker/volumes/*

- name: Run docker system prune
  sudo: yes
  ignore_errors: yes
  shell: docker system prune -f
