---
- name: Stop and remove worker containers
  sudo: yes
  docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: yes
  with_items:
    - dispatcher-worker
    - build-worker
    - test-worker
    - delivery-worker

- name: Remove /opt/cccp-service directory
  sudo: yes
  file: path=/opt/cccp-service state=absent

- name: Remove images with no name or tag
  sudo: yes
  ignore_errors: yes
  shell: docker rmi $(docker images -f "dangling=true" -q)
