---
- name: Remove all running and exited other containers
  become: true
  shell: docker rm -f `docker ps -a -q`
  ignore_errors: yes

- name: Remove all images
  become: true
  shell: docker rmi -f `docker images -a -q`
  ignore_errors: yes

- name: Remove mounts
  become: true
  shell: for f in `mount | grep origin | cut -f3 -d\ `; do umount $f ; done
  ignore_errors: yes

- name: Remove /var/lib/origin/* directory contents
  become: true
  shell: rm -rf /var/lib/origin/*

- name: Remove images with no name or tag
  become: true
  ignore_errors: yes
  shell: docker rmi $(docker images -f "dangling=true" -q)
