---
- name: Ensure dependencies are installed.
  yum: pkg=curl state=installed

- name: Ensure Jenkins repo is installed.
  copy:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"

- name: Ensure Jenkins is installed.
  yum: name=jenkins-2.67-1.1 state=present

- name: Reload jenkins systemd service
  sudo: yes
  systemd: name=jenkins state=reloaded

- name: Ensure jenkins is enabled and started
  systemd: name=jenkins state=started enabled=yes
