- include: install.yml
  tags:
  - jenkins/master

# Stop Jenkins so no files are overriden by a running Jenkins instance
- name: Stop jenkins before configuration
  service: name=jenkins state=stopped
  sudo: yes
  tags:
  - jenkins/master

- include: config.yml
  tags:
  - jenkins/master

# Start Jenkins again
- name: Start jenkins
  service: name=jenkins state=started
  sudo: yes
  tags:
  - jenkins/master

- name: Wait for Jenkins to come up
  wait_for:
    host: '{{ansible_default_ipv4.address}}'
    port: 8080
    delay: 5
    timeout: 300
  tags:
    - jenkins/master

- name: Wait for Jenkins UI to come up
  shell: curl --head --silent http://{{ ansible_default_ipv4.address }}:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 50
  delay: 5
  tags:
    - jenkins/master

- include: plugins.yml
  tags:
    - jenkins/master

- name: restart jenkins
  service: name=jenkins state=restarted enabled=yes
  tags:
    - jenkins/master

- name: Wait for Jenkins to come up
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: 8080
    delay: 5
    timeout: 300
  tags:
    - jenkins/master

- name: Wait for Jenkins UI to come up
  shell: curl --head --silent http://{{ ansible_default_ipv4.address }}:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 50
  delay: 5
  tags:
    - jenkins/master

- include: jobs.yml
  tags:
    - jenkins
    - jobs
    - jenkins/master

- name: Copy script to monitor access to Jenkins slave from master using Zabbix
  template: src=cron_check_slave_uptime.sh.j2 dest=/root/cron_check_slave_uptime.sh mode=0755
  tags:
    - jenkins
    - monitor
    - jenkins/master

- name: Cronjob to check if Jenkins slave is up, every minute
  cron: name="check jenkins slave access" job="/root/cron_check_slave_uptime.sh"
  tags:
    - jenkins
    - monitor
    - jenkins/master

- include: logrotate.yml
  tags:
    - jenkins
    - jenkins/master
    - logrotate
