apiVersion: "v1"
kind: "Template"
metadata:
  name: "container-pipeline-ci-job"
objects:
  - apiVersion: "v1"
    kind: "BuildConfig"
    metadata:
        name: ci-job
    spec:
      source:
        type: Git
        git:
          uri: ${CI_PIPELINE_REPO}
          ref: ${CI_PIPELINE_BRANCH}
        contextDir: "ci"
      strategy:
        type: "JenkinsPipeline"
        jenkinsPipelineStrategy:
          jenkinsfilePath: "Jenkinsfile"
          env:
          - name: CI_PIPELINE_REPO
            value: ${CI_PIPELINE_REPO}
          - name: CI_PIPELINE_BRANCH
            value: ${CI_PIPELINE_BRANCH}
parameters:
- description: Repository containing CentOS Container Pipeline service code
  displayName: Pipeline service repo
  name: CI_PIPELINE_REPO
  required: true
- description: Branch of Pipeline service to checkout to
  displayName: Pipeline branch
  name: CI_PIPELINE_BRANCH
  required: true
